### ISSUE TITLE
long texts end up out of the view

### ISSUE THREAD

**Issue by robmr88** [kalaganov/corner_decoration#1]
Hi, is there a way to make sure that the text fits in the badge?

**Comment by kalaganov** [comment]
unlikely
even assuming it's possible what's the benefit of this?

**Comment by robmr88** [comment]
the benefit would be that a longer than expected text would not go outside the view. I'm not talking about thousands of characters long but a slightly longer text. it would be useful when the text loaded in the banner is dynamic , some string that comes from a server for example , you can't know what string you will get . It would be interesting if AutosizeText could be integrated in this widget

**Comment by Gurjot95** [comment]
I would suggest you to use [AutoSizeText](https://pub.dev/packages/auto_size_text) widget for your requirement.

**Comment by robmr88** [comment]
The widget does not take another widget in input to display the text, you can only pass it the String
